[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "public"  # Adjust if your Flask app generates static files to a different directory

[dev]
  command = "python app.py"
